username= Admin
password= admin123
url=https://www.epexspot.com/en/market-results?market_area=GB&auction=&delivery_date=2026-03-25&underlying_year=&modality=Continuous&sub_modality=&technology=&data_mode=table&period=&production_period=&product=30